# Build settings
markdown: redcarpet
highlighter: pygments
gems:
  - jemoji
  
# Site settings
title: "EPIC GIS"
description: > # this means to ignore newlines until "email:"
   The Epidemiology and Population Health Summer Institute at Columbia University - Geographic Information Systems Course

email: a-mail@mail.mail
#blog logo
logo: "/assets/images/globe.png"
# blog cover
cover: "/assets/images/crashes.png"

name: 'Daniel M. Sheehan'
author: 'Daniel M. Sheehan'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://epic-gis.github.io/" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  # - icon:	twitter
  #   url:	https://twitter.com/nygeog
  #   desc: Follow me on twitter
  #   share_url: http://twitter.com/share
  #   share_title: ?text=
  #   share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/epic-gis
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
